### ISSUE TITLE
Would it be possible to do the same for other media types - i.e books or movies?

### ISSUE THREAD

**Issue by GuyGieri** [adriansteffan/notion-videogame-gallery#1]

**Comment by adriansteffan** [comment]
As this project just glues together calls to apis serving information on video games and feeds the results into the notion api, that would be doable. I am not super interested in doing that right now, but there are several other projects doing this. For example, check out https://www.reddit.com/r/Notion/comments/rqmowq/release_notion_watchlist_powered_by_api_public/?utm_source=share&utm_medium=ios_app&utm_name=iossmf for movies and https://onesprintatatime.com/building-my-digital-bookshelf for books.
